server:
  port: 8081

spring:
  docker:
    compose:
      enabled: true
      file: compose.yaml
  
  cloud:
    aws:
      secretsmanager:
        enabled: false
    stream:
      kafka:
        binder:
          brokers: localhost:19092
